spring.application.name=cevig

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.datasource.url = jdbc:mysql://${mySqlRuta}:3306/${dbProyecto}
spring.datasource.username = ${dbUsuario}
spring.datasource.password = ${dbContrasena}
